#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Installer Utility Module

This module contains utilities for creating a Windows installer for the PhishGuard application.
"""

import os
import sys
import logging
import subprocess

logger = logging.getLogger('PhishGuard.Installer')


def create_installer():
    """Create a Windows installer for the PhishGuard application
    
    This function uses PyInstaller to create a standalone executable and
    then packages it into a Windows installer using NSIS.
    
    Returns:
        bool: True if the installer was created successfully, False otherwise
    """
    try:
        # Get the project root directory
        project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        
        # Create the PyInstaller command
        pyinstaller_cmd = [
            'pyinstaller',
            '--name=PhishGuard',
            '--windowed',
            '--icon=resources/icon.ico',
            '--add-data=resources;resources',
            '--hidden-import=win32gui',
            '--hidden-import=win32process',
            '--hidden-import=win32con',
            '--hidden-import=win32api',
            '--hidden-import=win32com',
            '--hidden-import=win32com.client',
            '--hidden-import=win32com.server',
            '--hidden-import=pythoncom',
            '--hidden-import=psutil',
            '--hidden-import=requests',
            '--hidden-import=bs4',
            '--hidden-import=lxml',
            '--hidden-import=sklearn',
            '--hidden-import=numpy',
            '--hidden-import=pandas',
            '--onefile',
            os.path.join(project_root, 'main.py')
        ]
        
        # Run PyInstaller
        logger.info("Running PyInstaller...")
        subprocess.run(pyinstaller_cmd, cwd=project_root, check=True)
        
        # Create the NSIS script
        nsis_script = os.path.join(project_root, 'installer.nsi')
        with open(nsis_script, 'w') as f:
            f.write("""
            ; PhishGuard Installer Script
            ; Generated by PhishGuard Installer Utility
            
            !include "MUI2.nsh"
            
            ; General
            Name "PhishGuard"
            OutFile "PhishGuard-Setup.exe"
            InstallDir "$PROGRAMFILES\\PhishGuard"
            InstallDirRegKey HKCU "Software\\PhishGuard" ""
            RequestExecutionLevel admin
            
            ; Interface Settings
            !define MUI_ABORTWARNING
            !define MUI_ICON "${NSISDIR}\\Contrib\\Graphics\\Icons\\modern-install.ico"
            !define MUI_UNICON "${NSISDIR}\\Contrib\\Graphics\\Icons\\modern-uninstall.ico"
            
            ; Pages
            !insertmacro MUI_PAGE_WELCOME
            !insertmacro MUI_PAGE_DIRECTORY
            !insertmacro MUI_PAGE_INSTFILES
            !insertmacro MUI_PAGE_FINISH
            
            !insertmacro MUI_UNPAGE_CONFIRM
            !insertmacro MUI_UNPAGE_INSTFILES
            
            ; Languages
            !insertmacro MUI_LANGUAGE "English"
            
            ; Installer Sections
            Section "PhishGuard" SecPhishGuard
                SetOutPath "$INSTDIR"
                
                ; Add files
                File "dist\\PhishGuard.exe"
                File "README.md"
                
                ; Create uninstaller
                WriteUninstaller "$INSTDIR\\Uninstall.exe"
                
                ; Create shortcuts
                CreateDirectory "$SMPROGRAMS\\PhishGuard"
                CreateShortcut "$SMPROGRAMS\\PhishGuard\\PhishGuard.lnk" "$INSTDIR\\PhishGuard.exe"
                CreateShortcut "$SMPROGRAMS\\PhishGuard\\Uninstall.lnk" "$INSTDIR\\Uninstall.exe"
                CreateShortcut "$DESKTOP\\PhishGuard.lnk" "$INSTDIR\\PhishGuard.exe"
                
                ; Add to Add/Remove Programs
                WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\PhishGuard" "DisplayName" "PhishGuard"
                WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\PhishGuard" "UninstallString" "$\"$INSTDIR\\Uninstall.exe$\""
                WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\PhishGuard" "QuietUninstallString" "$\"$INSTDIR\\Uninstall.exe$\" /S"
                WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\PhishGuard" "InstallLocation" "$\"$INSTDIR$\""
                WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\PhishGuard" "DisplayIcon" "$\"$INSTDIR\\PhishGuard.exe$\""
                WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\PhishGuard" "Publisher" "PhishGuard"
                WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\PhishGuard" "DisplayVersion" "1.0.0"
                WriteRegDWORD HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\PhishGuard" "NoModify" 1
                WriteRegDWORD HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\PhishGuard" "NoRepair" 1
                
            SectionEnd
            
            ; Uninstaller Section
            Section "Uninstall"
                ; Remove files
                Delete "$INSTDIR\\PhishGuard.exe"
                Delete "$INSTDIR\\README.md"
                Delete "$INSTDIR\\Uninstall.exe"
                
                ; Remove shortcuts
                Delete "$SMPROGRAMS\\PhishGuard\\PhishGuard.lnk"
                Delete "$SMPROGRAMS\\PhishGuard\\Uninstall.lnk"
                Delete "$DESKTOP\\PhishGuard.lnk"
                RMDir "$SMPROGRAMS\\PhishGuard"
                
                ; Remove registry keys
                DeleteRegKey HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\PhishGuard"
                DeleteRegKey HKCU "Software\\PhishGuard"
                
                ; Remove installation directory
                RMDir "$INSTDIR"
            SectionEnd
            """)
        
        # Create a simple README.md file if it doesn't exist
        readme_file = os.path.join(project_root, 'README.md')
        if not os.path.exists(readme_file):
            readme_content = """# PhishGuard

PhishGuard is a Windows application that helps protect you from phishing websites.
It monitors your web browsers and alerts you when it detects a potential phishing site.

## Features

- Real-time browser monitoring
- Advanced phishing detection
- Customizable alert settings
- System tray integration

## Installation

1. Run the installer and follow the on-screen instructions
2. PhishGuard will start automatically after installation

## Usage

PhishGuard runs in the background and monitors your web browsers. When it detects a
potential phishing site, it will display an alert and optionally block access to the site.

You can access the PhishGuard interface by clicking on the system tray icon.
"""
            with open(readme_file, 'w') as f:
                f.write(readme_content)

        # Convert SVG icon to ICO for Windows
        # In a real implementation, you would use a library like cairosvg or Pillow
        # For this example, we'll just copy the SVG file
        import shutil
        svg_icon = os.path.join(project_root, 'resources', 'icon.svg')
        ico_icon = os.path.join(project_root, 'resources', 'icon.ico')
        shutil.copy(svg_icon, ico_icon)
        
        # Run NSIS to create the installer
        nsis_cmd = ['makensis', 'installer.nsi']
        logger.info("Running NSIS to create the installer...")
        subprocess.run(nsis_cmd, cwd=project_root, check=True)
        
        logger.info("Installer created successfully!")
        return True
        
    except subprocess.CalledProcessError as e:
        logger.error(f"Error running command: {e}")
        return False
    except Exception as e:
        logger.error(f"An unexpected error occurred: {e}")
        return False


if __name__ == "__main__":
    # Set up logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    # Create the installer
    success = create_installer()
    
    # Exit with appropriate code
    sys.exit(0 if success else 1)